// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using brokerApp.API.Data;

#nullable disable

namespace brokerApp.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260714115228_AddClawbackColumnsToStatementItem")]
    partial class AddClawbackColumnsToStatementItem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdvisorAdvisorGroup", b =>
                {
                    b.Property<int>("AdvisorGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("MembersId")
                        .HasColumnType("integer");

                    b.HasKey("AdvisorGroupId", "MembersId");

                    b.HasIndex("MembersId");

                    b.ToTable("AdvisorGroupMembers", (string)null);
                });

            modelBuilder.Entity("AdvisorPolicyRecord", b =>
                {
                    b.Property<int>("AdvisorsId")
                        .HasColumnType("integer");

                    b.Property<string>("PolicyRecordPolicyNumber")
                        .HasColumnType("text");

                    b.HasKey("AdvisorsId", "PolicyRecordPolicyNumber");

                    b.HasIndex("PolicyRecordPolicyNumber");

                    b.ToTable("PolicyAdvisors", (string)null);
                });

            modelBuilder.Entity("AdvisorSubmission", b =>
                {
                    b.Property<int>("AdvisorsId")
                        .HasColumnType("integer");

                    b.Property<int>("SubmissionsId")
                        .HasColumnType("integer");

                    b.HasKey("AdvisorsId", "SubmissionsId");

                    b.HasIndex("SubmissionsId");

                    b.ToTable("SubmissionAdvisors", (string)null);
                });

            modelBuilder.Entity("brokerApp.API.Models.AccountAdjustment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdvisorGroupId")
                        .HasColumnType("integer");

                    b.Property<int?>("AdvisorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateIncurred")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PromotionalItemId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("RemainingBalance")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TargetMonthlyRepayment")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdvisorGroupId");

                    b.HasIndex("AdvisorId");

                    b.HasIndex("PromotionalItemId");

                    b.ToTable("AccountAdjustments");
                });

            modelBuilder.Entity("brokerApp.API.Models.Advisor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("CommissionPercentage1stYear")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CommissionPercentage2ndYear")
                        .HasColumnType("numeric");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirebaseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Advisors");
                });

            modelBuilder.Entity("brokerApp.API.Models.AdvisorCommission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountAdjustmentId")
                        .HasColumnType("integer");

                    b.Property<int>("AdvisorId")
                        .HasColumnType("integer");

                    b.Property<decimal>("CommissionAmount")
                        .HasColumnType("numeric");

                    b.Property<int?>("CommissionStatementId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCalculated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DatePaid")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<string>("PayoutReference")
                        .HasColumnType("text");

                    b.Property<int?>("PolicyPaymentId")
                        .HasColumnType("integer");

                    b.Property<int?>("SubmissionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountAdjustmentId");

                    b.HasIndex("AdvisorId");

                    b.HasIndex("CommissionStatementId");

                    b.HasIndex("PolicyPaymentId");

                    b.HasIndex("SubmissionId");

                    b.ToTable("AdvisorCommissions");
                });

            modelBuilder.Entity("brokerApp.API.Models.AdvisorGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AdvisorGroups");
                });

            modelBuilder.Entity("brokerApp.API.Models.CommissionStatement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EmailSentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileUrl")
                        .HasColumnType("text");

                    b.Property<string>("GoogleSheetUrl")
                        .HasColumnType("text");

                    b.Property<int>("MatchedRows")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StatementDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalCommission")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalRows")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CommissionStatements");
                });

            modelBuilder.Entity("brokerApp.API.Models.MovementItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdvisorName")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CommissionStatementId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EffectiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileUrl")
                        .HasColumnType("text");

                    b.Property<string>("GoogleDriveLink")
                        .HasColumnType("text");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int?>("MatchedSubmissionId")
                        .HasColumnType("integer");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Premium")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CommissionStatementId");

                    b.HasIndex("MatchedSubmissionId");

                    b.ToTable("MovementItems");
                });

            modelBuilder.Entity("brokerApp.API.Models.PolicyPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountReceived")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DateReceived")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId");

                    b.ToTable("PolicyPayments");
                });

            modelBuilder.Entity("brokerApp.API.Models.PolicyRecord", b =>
                {
                    b.Property<string>("PolicyNumber")
                        .HasColumnType("text");

                    b.Property<int?>("AdvisorGroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LastCommissionAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Premium")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PolicyNumber");

                    b.HasIndex("AdvisorGroupId");

                    b.ToTable("PolicyRecords");
                });

            modelBuilder.Entity("brokerApp.API.Models.PromotionalItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Sizes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PromotionalItems");
                });

            modelBuilder.Entity("brokerApp.API.Models.StatementItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdvisorName")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("ClawBack")
                        .HasColumnType("numeric");

                    b.Property<string>("ClawBackReason")
                        .HasColumnType("text");

                    b.Property<decimal?>("ClawBackRetention")
                        .HasColumnType("numeric");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CommissionStatementId")
                        .HasColumnType("integer");

                    b.Property<string>("CommissionSubType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CommissionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileUrl")
                        .HasColumnType("text");

                    b.Property<string>("GoogleDriveLink")
                        .HasColumnType("text");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int?>("MatchedSubmissionId")
                        .HasColumnType("integer");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Premium")
                        .HasColumnType("numeric");

                    b.Property<string>("SalesForceName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CommissionStatementId");

                    b.HasIndex("MatchedSubmissionId");

                    b.ToTable("StatementItems");
                });

            modelBuilder.Entity("brokerApp.API.Models.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdvisorGroupId")
                        .HasColumnType("integer");

                    b.Property<string>("ApplicantPhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicantSurname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Method")
                        .HasColumnType("integer");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Premium")
                        .HasColumnType("numeric");

                    b.Property<string>("SalaryRefNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdvisorGroupId");

                    b.HasIndex("ApplicantSurname");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ApplicantSurname"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("ApplicantSurname"), new[] { "gin_trgm_ops" });

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Initials");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Initials"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Initials"), new[] { "gin_trgm_ops" });

                    b.HasIndex("PolicyNumber");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("PolicyNumber"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("PolicyNumber"), new[] { "gin_trgm_ops" });

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("brokerApp.API.Models.SubmissionDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId");

                    b.ToTable("SubmissionDocuments");
                });

            modelBuilder.Entity("AdvisorAdvisorGroup", b =>
                {
                    b.HasOne("brokerApp.API.Models.AdvisorGroup", null)
                        .WithMany()
                        .HasForeignKey("AdvisorGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("brokerApp.API.Models.Advisor", null)
                        .WithMany()
                        .HasForeignKey("MembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AdvisorPolicyRecord", b =>
                {
                    b.HasOne("brokerApp.API.Models.Advisor", null)
                        .WithMany()
                        .HasForeignKey("AdvisorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("brokerApp.API.Models.PolicyRecord", null)
                        .WithMany()
                        .HasForeignKey("PolicyRecordPolicyNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AdvisorSubmission", b =>
                {
                    b.HasOne("brokerApp.API.Models.Advisor", null)
                        .WithMany()
                        .HasForeignKey("AdvisorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("brokerApp.API.Models.Submission", null)
                        .WithMany()
                        .HasForeignKey("SubmissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("brokerApp.API.Models.AccountAdjustment", b =>
                {
                    b.HasOne("brokerApp.API.Models.AdvisorGroup", "AdvisorGroup")
                        .WithMany()
                        .HasForeignKey("AdvisorGroupId");

                    b.HasOne("brokerApp.API.Models.Advisor", "Advisor")
                        .WithMany("Adjustments")
                        .HasForeignKey("AdvisorId");

                    b.HasOne("brokerApp.API.Models.PromotionalItem", "PromotionalItem")
                        .WithMany()
                        .HasForeignKey("PromotionalItemId");

                    b.Navigation("Advisor");

                    b.Navigation("AdvisorGroup");

                    b.Navigation("PromotionalItem");
                });

            modelBuilder.Entity("brokerApp.API.Models.AdvisorCommission", b =>
                {
                    b.HasOne("brokerApp.API.Models.AccountAdjustment", "AccountAdjustment")
                        .WithMany()
                        .HasForeignKey("AccountAdjustmentId");

                    b.HasOne("brokerApp.API.Models.Advisor", "Advisor")
                        .WithMany()
                        .HasForeignKey("AdvisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("brokerApp.API.Models.CommissionStatement", "CommissionStatement")
                        .WithMany()
                        .HasForeignKey("CommissionStatementId");

                    b.HasOne("brokerApp.API.Models.PolicyPayment", "PolicyPayment")
                        .WithMany("Commissions")
                        .HasForeignKey("PolicyPaymentId");

                    b.HasOne("brokerApp.API.Models.Submission", "Submission")
                        .WithMany()
                        .HasForeignKey("SubmissionId");

                    b.Navigation("AccountAdjustment");

                    b.Navigation("Advisor");

                    b.Navigation("CommissionStatement");

                    b.Navigation("PolicyPayment");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("brokerApp.API.Models.MovementItem", b =>
                {
                    b.HasOne("brokerApp.API.Models.CommissionStatement", "Statement")
                        .WithMany("MovementItems")
                        .HasForeignKey("CommissionStatementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("brokerApp.API.Models.Submission", "MatchedSubmission")
                        .WithMany()
                        .HasForeignKey("MatchedSubmissionId");

                    b.Navigation("MatchedSubmission");

                    b.Navigation("Statement");
                });

            modelBuilder.Entity("brokerApp.API.Models.PolicyPayment", b =>
                {
                    b.HasOne("brokerApp.API.Models.Submission", "Submission")
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("brokerApp.API.Models.PolicyRecord", b =>
                {
                    b.HasOne("brokerApp.API.Models.AdvisorGroup", "AdvisorGroup")
                        .WithMany()
                        .HasForeignKey("AdvisorGroupId");

                    b.Navigation("AdvisorGroup");
                });

            modelBuilder.Entity("brokerApp.API.Models.StatementItem", b =>
                {
                    b.HasOne("brokerApp.API.Models.CommissionStatement", "Statement")
                        .WithMany("Items")
                        .HasForeignKey("CommissionStatementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("brokerApp.API.Models.Submission", "MatchedSubmission")
                        .WithMany()
                        .HasForeignKey("MatchedSubmissionId");

                    b.Navigation("MatchedSubmission");

                    b.Navigation("Statement");
                });

            modelBuilder.Entity("brokerApp.API.Models.Submission", b =>
                {
                    b.HasOne("brokerApp.API.Models.AdvisorGroup", "AdvisorGroup")
                        .WithMany("Submissions")
                        .HasForeignKey("AdvisorGroupId");

                    b.Navigation("AdvisorGroup");
                });

            modelBuilder.Entity("brokerApp.API.Models.SubmissionDocument", b =>
                {
                    b.HasOne("brokerApp.API.Models.Submission", "Submission")
                        .WithMany("Documents")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("brokerApp.API.Models.Advisor", b =>
                {
                    b.Navigation("Adjustments");
                });

            modelBuilder.Entity("brokerApp.API.Models.AdvisorGroup", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("brokerApp.API.Models.CommissionStatement", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("MovementItems");
                });

            modelBuilder.Entity("brokerApp.API.Models.PolicyPayment", b =>
                {
                    b.Navigation("Commissions");
                });

            modelBuilder.Entity("brokerApp.API.Models.Submission", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
